### ISSUE TITLE
Comments visible on restricted lessons, before drip.

### ISSUE THREAD

**Issue by jenhooks** [woocommerce/sensei-content-drip#139]
In 1221589-zen, the user reports that comments are visible on lessons that haven't dripped to users yet. This is a concern for the user, since he interacts with his students in the comments by answering questions about the restricted content. 

I was able to reproduce on his site and my own test site, using Storefront:

**His site:**
<img width="857" alt="user_comments_visible" src="https://user-images.githubusercontent.com/7585054/41866236-8d63b196-787d-11e8-9259-742318315a64.png">

**My test site:**
<img width="915" alt="my_comments_visible" src="https://user-images.githubusercontent.com/7585054/41866263-9f01d306-787d-11e8-80ea-547003b4cd31.png">

**To reproduce:**

1. Make sure Sensei > Settings > Lessons > Allow Comments for Lessons is selected.
2. Create a course two lessons, the first immediately available, the second one scheduled to drip.
3. Add test comment. If you don't see the comment meta box available on the Lesson edit page, you may need to enable comments under Screen Options (top right). 
3. Add a test Learner user to the course under Learner Management.
4. View the course while logged in as the Learner, you should be able to see the lesson content on the first lesson, as well as the comment. When you try to view the second lesson, you'll be notified that the lesson hasn't become available yet, but you _will_ be able to view the comment.

**Comment by gkaragia** [comment]
Hey @donnapep,

I have run some tests around the comments functionality and I think that if we are going to implement this we need to restrict viewing comments in a more broad sense.

So to be more specific, as long as commenting is allowed to lessons, the comments are always visible. For example the comments are visible in the following cases:

- The user has not bought the lesson
- The user is not logged in
- The content is restricted due to content drip.

To me this means that comments are part of a lesson's unrestriced information which is always visible. If we are going to implement this I think that we need to tie comments with the actual content so whenever the content is restricted the comments would be too. That means that we shouldn't treat this issue as bug but as a new feature instead. Let me know your thoughts.

**Comment by donnapep** [comment]
There's actually another setting at play here. In _Sensei LMS_ > _Settings_, ensure the _Access Permissions_ checkbox is selected. That will prevent comments from showing for users who have not started the course or are not logged in.

Content that has not dripped yet should ignore the _Access Permissions_ setting altogether and never show comments.

**Comment by gkaragia** [comment]
Indeed, I had this setting disabled 😅 I can see the issue after enabling it.
