### ISSUE TITLE
Video and buttons hidden after completing lesson

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-content-drip#92]
**What I expected:**
Logged in a subscriber. When viewing a lesson containing a video, when I click "Complete Lesson" the video should still be visible.

**What I saw:**
When I click "Complete Lesson" the video is no longer visible. Also if there is a quiz, the "View Lesson Quiz" and "Reset Lesson" buttons are not visible.

![image](https://cloud.githubusercontent.com/assets/1990037/13460240/4baf8d66-e071-11e5-8fb3-8072da2ac70d.png)

If you deactivate Content Drip, the video and buttons are visible again:
![image](https://cloud.githubusercontent.com/assets/1990037/13460355/ed099bc0-e071-11e5-8bce-b3c6198178b5.png)
- 391122-zd-woothemes
- 384154-zd-woothemes
- 394344-zd-woothemes

**Comment by richardmtl** [comment]
This issue seems to be back. I was able to reproduce it on a user's site, with just Sensei, Content Drip, and Twenty Sixteen active. 417404-zd-woothemes

**Comment by richardmtl** [comment]
Another report in 425754-zd-woothemes. In this case though there's no video content in the Lesson. Also, according to the user, Content Drip 1.0.4 works as expected.

**Comment by richardmtl** [comment]
In 430269-zd-woothemes the user says:

> If I turn on WP_DEBUG I get three main messages:

>Notice: Undefined offset: 0 in /www/wp-includes/query.php on line 3848

>Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/includes/class-sensei-lesson.php on line 3686

>Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/templates/globals/pagination-lesson.php on line 13 Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/includes/class-sensei-modules.php on line 485

**Comment by georgestephanis** [comment]
> Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/includes/class-sensei-lesson.php on line 3686

https://github.com/Automattic/sensei/blob/4deae19/includes/class-sensei-lesson.php#L3686

> Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/templates/globals/pagination-lesson.php on line 13 Notice: Trying to get property of non-object in /www/wp-content/plugins/woothemes-sensei/includes/class-sensei-modules.php on line 485

https://github.com/Automattic/sensei/blob/4deae19/templates/globals/pagination-lesson.php#L13

---

Both of ^^ deal with the `$post` global being ... something other than an Object.  The cause of it not being a `WP_Post` object I don't know, yet.

**Comment by richardmtl** [comment]
Another report in 437518-zd-woothemes

**Comment by rachelsquirrel** [comment]
Another report in 436934-zd-woothemes

**Comment by rachelsquirrel** [comment]
Another report in 444501-zd-woothemes

**Comment by georgestephanis** [comment]
Still digging, but I think it tracks back to https://github.com/woothemes/sensei-content-drip/blob/37d6ff60767f670b2aacc2c1edb22e858c5e81fc/includes/class-scd-ext-lesson-frontend.php#L84-L100

**Comment by georgestephanis** [comment]
I'm not *quite* sure why, but it seems that when it's meant to be testing if a lesson can be viewed, it's actually testing the subsequent lesson (I get by checking the ID tested inside `is_dynamic_drip_type_content_blocked`)

It looks like the problem happens when that runs during the `wp_head` action rather than during the body (which seems to happen on the initial POST request, rather than subsequent GET requests) -- specifically when `Sensei_Utils::user_complete_course()` is called.

I suspect this is a side effect of the `Scd_Ext_Lesson_Frontend::lesson_content_drip_filter()` which messes with the `$wp_query` global directly running on `the_posts` filter which is called down the stack from `Sensei_Utils::user_complete_course()` so that the post is removed too early, and when the body starts, there are no posts available.

cc: @dwainm for input -- some of the history of related code has your name on it, wanted to see if any of this means more to you than it does to me offhand?

**Comment by dwainm** [comment]
@georgestephanis off hand what you saying seems correct. If a lesson is not available to be view we show another template and thus mess with the query. I haven't worked on this in a few months but can do some more digging for you later this week.

**Comment by rachelsquirrel** [comment]
I am able to reproduce this so just making a note of the steps:

1. Create a course.
2. Add two lessons to the course.
3. Make the first lesson available immediately and drip the content for the second lesson to be a specific interval after the course start date (I chose 4 days). 
4. Sign in as a subscriber and start taking the course. After the first lesson is complete click "Complete Lesson". A blank page loads and there's no notice saying when the next lesson will become available or a link back to the main course page.

**Comment by georgestephanis** [comment]
Honestly, as the issue is only present on POST form submissions, but not subsequent GET requests, the simplest method may be to just `wp_safe_redirect()` to the page from itself after the initial processing.  The problem is that the initial processing seems to happen at `wp_head` instead of something before output like `template_redirect` or `wp_load`

I don't have time to finish this off before I rotate off of Guardians, but my recommendation is to:

1) Shift the processing from `wp_head` to `wp_load` or an earlier hook, so we can
2) `wp_safe_redirect()` back to a GET version of the page that wouldn't exhibit the difficulty.

**Comment by jenhooks** [comment]
Seeing this in 465479-zd-woothemes

**Comment by jenhooks** [comment]
Also 471189-zd-woothemes and 470185-zd-woothemes

**Comment by danjjohnson** [comment]
Had a follow up from a user waiting for a fix here.
@pgk or @dbtlr if you get chance to look into this any time soon, that would be great :)

**Comment by danjjohnson** [comment]
481641-zd-woothemes

**Comment by lvnilesh** [comment]
https://github.com/Automattic/sensei/issues/1597

**Comment by lvnilesh** [comment]
Appreciate your help @pgk and @dbtlr if you can please investigate. Thanks.

**Comment by lvnilesh** [comment]
I am going to `git checkout version/1.0.4` as a workaround in the interim.

**Comment by danjjohnson** [comment]
484342-zd-woothemes

**Comment by pgk** [comment]
Seems this interacts badly with sensei-course-participants and sensei-course-progress too. Similar notices to the POST case mentioned above, even on GET requests when those plugins are activated. The result is nothing showing on course viewing/completion

**Comment by pgk** [comment]
@lvnilesh @danjjohnson @rachelsquirrel can you try the solution in `fix/92-Content-Drip-Notices` (e.g. by doing `git fetch && git checkout fix/92-Content-Drip-Notices`)

**Comment by lvnilesh** [comment]
`fix/92-Content-Drip-Notices` worked 👍

**Comment by lvnilesh** [comment]
wp-content/plugins/sensei-content-drip/assets/css/frontend.css?ver=1.0.5 

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by pgk** [comment]
@lvnilesh should be ok now (you need to `git fetch && git checkout fix/92-Content-Drip-Notices && git reset --hard origin/fix/92-Content-Drip-Notices` if you want to use this branch)

**Comment by lvnilesh** [comment]
👍
